#! /bin/bash

### BEGIN INIT INFO
# Provides:          telescoped
# Required-Start:    $local_fs $remote_fs $network $syslog $named
# Required-Stop:     $local_fs $remote_fs $network $syslog $named
# Default-Start:     2 3 4 5
# Default-Stop:      0 1 6
# X-Interactive:     false
# Short-Description: Start/stop telescoped
### END INIT INFO

#set -e

. /lib/lsb/init-functions

if [[ ! -d "$TELESCOPED_DIR" ]]; then
    export TELESCOPED_DIR=/opt/telescoped
fi

#if [[ "$USER" == "root" ]]; then
#    TELESCOPED_USER="telescoped"
#else
#    TELESCOPED_USER="$USER"
#fi

TELESCOPED_USER="$USER"

PATH=/bin:/usr/bin:/sbin:/usr/sbin
HOME=/root
DAEMON=${TELESCOPED_DIR}/bin/telescoped
PIDFILE=${TELESCOPED_DIR}/run/telescoped.pid

export LOG4C_RCPATH="${TELESCOPED_DIR}/etc"

# Arguments to atd
#
ARGS=""

test -x $DAEMON || exit 0

case "$1" in
    start)
        log_action_begin_msg "Starting telescoped daemon"
        start-stop-daemon --start --quiet \
            --pidfile "$PIDFILE" \
            --chuid "$TELESCOPED_USER" \
            --exec "$DAEMON" -- $ARGS
        log_action_end_msg $?
        ;;
    stop)
        log_action_begin_msg "Stopping telescoped daemon"
        start-stop-daemon --stop --quiet --pidfile "$PIDFILE"
        log_action_end_msg $?
        ;;
    restart|force-reload)
        "$0" stop
        sleep 2
        "$0" start
        ;;
    *)
        echo "Usage: $0 {start|stop|restart|force-reload}"
        exit 1
        ;;
esac

exit 0
