#!/bin/bash

### BEGIN INIT INFO
# Provides:          exposed-frodo
# Required-Start:    $spectrographd $telescoped 
# Required-Stop:     $spectrographd $telescoped
# Default-Start:     2 3 4 5
# Default-Stop:      0 1 6
# X-Interactive:     false
# Short-Description: Start/stop exposed-frodo
### END INIT INFO

# Deactivate exposed-frodo
#exit 0

SCRIPT_NAME=$(basename $0)
CCD_NAME=${SCRIPT_NAME#*exposed-}

SVN_REV="646"

if [[ ! -d "$EXPOSED_DIR" ]]; then
    export EXPOSED_DIR="/opt/exposed-r${SVN_REV}"
    rm -f /opt/exposed
    ln -s $EXPOSED_DIR /opt/exposed
fi

export HOME=/root
export LOG4C_RCPATH="${EXPOSED_DIR}/etc/${CCD_NAME}"
export TELESCOPE_HOST="primula"
export TELESCOPE_PORT="9999"
export SPECTROGRAPH_HOST="primula"
export SPECTROGRAPH_PORT="8888"

## WARNING: LD_LIBRARY_PATH nastavuje skript set_picam_env
#export LD_LIBRARY_PATH=/opt/exposed/lib

EXPOSED_SERVER_PATH="${EXPOSED_DIR}/bin/exposed"
EXPOSED_SERVER_PID_PATH="${EXPOSED_DIR}/run/exposed-${CCD_NAME}.pid"

if [ -x $EXPOSED_SERVER_PATH ]; then
  echo -n
else
  echo "$EXPOSED_SERVER_PATH not exist or not access permissions run"
  exit 0
fi

case $1 in
    start)
        EXPOSED_PID=$(cat $EXPOSED_SERVER_PID_PATH 2>/dev/null)
        if [ $? -eq 0 ]; then
        
            READLINK_PROC_EXE=$(readlink "/proc/${EXPOSED_PID}/exe" 2>/dev/null)
            if [ $? -eq 0 ]; then
        
                BASENAME_PROC_EXE=$(basename $READLINK_PROC_EXE 2>/dev/null)
                if [ $? -eq 0 ]; then
        
                    if [ "$BASENAME_PROC_EXE" == "exposed" ]; then
                        echo "$EXPOSED_SERVER_PATH is already running"
                        exit 0
                    fi
                fi
            else
                echo "PID $EXPOSED_PID does not exist"
            fi
        
            echo "Remove $EXPOSED_SERVER_PID_PATH"
            rm $EXPOSED_SERVER_PID_PATH
        fi
   
        echo "Starting exposed"
        #/opt/peso/bin/ccd400_lock

        $EXPOSED_SERVER_PATH -d -c ${EXPOSED_DIR}/etc/exposed-${CCD_NAME}.cfg

        # DBG
        #$EXPOSED_SERVER_PATH -c ${EXPOSED_DIR}/etc/exposed-${CCD_NAME}.cfg
        #echo "-c ${EXPOSED_DIR}/etc/exposed-${CCD_NAME}.cfg"
        #gdb $EXPOSED_SERVER_PATH
    ;;
    stop)
        echo "Stopping exposed"
        EXPOSED_PID=$(cat $EXPOSED_SERVER_PID_PATH)
        kill $EXPOSED_PID

        i=0
        while kill -0 $EXPOSED_PID 2>/dev/null;  do
            if [ $i -ge 60 ]; then
                break;
            else
                echo -n "."
                i=$(($i+1))
                sleep 1
            fi
        done

        #/opt/peso/bin/ccd400_unlock
    ;;
    *)
        echo "Usage: /etc/init.d/exposed start|stop"
    ;;
esac
